# Generated by Django 3.2.7 on 2021-09-21 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('file_code', models.CharField(max_length=11000)),
                ('file_upload', models.FileField(upload_to=upload.validators.upload_file_path, validators=[upload.validators.upload_file_validator])),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
